<a href="https://colab.research.google.com/github/cblee044/Learning_TensorFlow/blob/main/00_tf_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we will cover the fundamentals of tensors in TensorFlow

MOre specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and numpy
* Using atf function(a way to speed up your regular python features)
* Using GPUs with TensorFlow
* Exercises to try for yourself

# Introduction to Tensors

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions

### Creating Random Tensors


In [ ]:
# First create the random generator and then call a distribution from it.
random_1 = tf.random.Generator.from_seed(42)
random_2 = random_1.uniform(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [ ]:
### Shuffle the order of tensors
# Important so the machine can learn without bias from the order

In [ ]:
# Shuffle a tensor
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,6]])

# Shuffles elements column-wise
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  6],
       [10,  7],
       [ 3,  4]], dtype=int32)>

### If you want the same results for every re-run of tensor flow, you need to set the global and operation seed

> If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.


### Turn Numpy arrays into TensorFlow tensors
The main difference between a Numpy array and a TensorFlow tensor is that tensors can be run on a GPU (much faster than a numpy array)

In [ ]:
import numpy as np
numpy_A = np.arange(0, 32, dtype=np.int32)
numpy_A

A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2,2,2,2,2))
B

<tf.Tensor: shape=(2, 2, 2, 2, 2), dtype=int32, numpy=
array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]], dtype=int32)>

### Indexing Tensors

Tensors can be indexed just like python lists.

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

# Section 2 Exercises
* Create a tensor of zeros of dim 2x3
* Create a tensor of all ones of dim 3x3x3x3
* Create a numpy array of dim 2x3 and turn into a tensor
* Create a numpy array of nx1 and turn into a tensor of dim rxc where r*c=n
* Reshape a tensor of dimensions nxm into a tensor of dimension rxc
* Create a tensor of your choice and grab its the shape, rank, dimension, and size.
* Create a rank 4 tensor and prove it.
* Grab the first element on the first axis
* Grab the second element on the first axis
* Grab the 4th row of the 2nd element in the 1st axis
* `

In [ ]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
tf.matmul(X, tf.reshape(Y, shape=(2,3)))
tf.matmul(X, tf.transpose(Y))
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [ ]:
print(tf.tensordot(X, tf.transpose(Y), axes=1))
print(tf.tensordot(X, tf.transpose(Y), axes=0))
print(tf.tensordot(X, tf.transpose(Y), axes=2))
print(tf.matmul(X, tf.transpose(Y)))

tf.Tensor(
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[[[ 7  9 11]
   [ 8 10 12]]

  [[14 18 22]
   [16 20 24]]]


 [[[21 27 33]
   [24 30 36]]

  [[28 36 44]
   [32 40 48]]]


 [[[35 45 55]
   [40 50 60]]

  [[42 54 66]
   [48 60 72]]]], shape=(3, 2, 2, 3), dtype=int32)
tf.Tensor(212, shape=(), dtype=int32)
tf.Tensor(
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]], shape=(3, 3), dtype=int32)


In [ ]:
B = tf.constant([1.4,3.4])
C = tf.constant([1.2,3.5], dtype=tf.float16)
print(f"The datatype of matrix B and C respectively is {B.dtype} and {C.dtype}")

The datatype of matrix B and C respectively is <dtype: 'float32'> and <dtype: 'float16'>


In [ ]:
B = tf.constant([[[2.3,4.3],
                 [3.4,2.3],
                 [3.4,1.4]]], dtype=tf.float16)

B.shape
tf.reduce_max(B, axis=2)

<tf.Tensor: shape=(1, 3), dtype=float16, numpy=array([[4.3, 3.4, 3.4]], dtype=float16)>

In [ ]:
C = tf.random.normal(shape=(2,3,2), mean=1, stddev=1, dtype=tf.float16)
print(C)
tf.reduce_max(C, axis=0)


tf.Tensor(
[[[-0.751  -0.1348]
  [ 1.168  -0.3691]
  [-0.676   1.698 ]]

 [[ 0.3872  1.615 ]
  [ 1.543   0.8877]
  [ 0.3755  1.816 ]]], shape=(2, 3, 2), dtype=float16)


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[0.3872, 1.615 ],
       [1.543 , 0.8877],
       [0.3755, 1.816 ]], dtype=float16)>

In [ ]:
tf.reduce_max(C, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 3, 2), dtype=float16, numpy=
array([[[0.3872, 1.615 ],
        [1.543 , 0.8877],
        [0.3755, 1.816 ]]], dtype=float16)>

In [ ]:
hours_slept = [6,6,7,8,6,6,5]
tf.one_hot(hours_slept, depth=8)

<tf.Tensor: shape=(7, 8), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)>